/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * AVM Trade Reporter API
 * # AVM Trade Reporter – Developer Guide
 *
 * ## Authentication (ARC-0014)
 *
 * Most endpoints in this API require **[ARC-0014](https://github.com/algorandfoundation/ARCs/issues/42)**
 * authentication ("Algorand transaction signature as authentication"). Instead of a username/password or
 * long-lived API key, the client signs a zero-fee, unbroadcast `NoOp`/payment-shaped Algorand transaction
 * whose `Note` field encodes a realm and expiry, then sends the signed transaction as the `Authorization`
 * header. The server verifies the signature and transaction validity window against Algorand node
 * transaction params — no signed transaction is ever submitted to the chain, it is purely a proof of key
 * ownership.
 *
 * - Realm for this API: `BiatecScan#ARC14`
 * - Header: `Authorization: SigTx <base64-encoded-signed-transaction>` (produced by the libraries below)
 * - The signed transaction's validity window (`firstValid`/`lastValid`) doubles as the token's expiry —
 *   there is no separate refresh step; the client just signs a new transaction with a fresh validity
 *   window when the old one expires
 * - Endpoints marked **"no authentication required"** below are intentionally public and accept
 *   unauthenticated requests
 *
 * ### Recommended client libraries
 *
 * - **JavaScript/TypeScript**: [`arc14`](https://www.npmjs.com/package/arc14) (builds and signs the
 *   ARC-14 transaction, produces the `Authorization` header value) together with
 *   [`arc76`](https://www.npmjs.com/package/arc76) (deterministic Algorand keypair derivation, if the
 *   client needs a stable identity without a wallet) and [`algosdk`](https://www.npmjs.com/package/algosdk)
 *   for transaction params/signing primitives. Example:
 *   ```ts
 *   import algosdk from "algosdk";
 *   import { makeArc14AuthHeader, makeArc14TxWithSuggestedParams } from "arc14";
 *
 *   const tx = await makeArc14TxWithSuggestedParams("BiatecScan#ARC14", account.addr.toString(), suggestedParams);
 *   const signed = tx.signTxn(account.sk);
 *   const authorizationHeader = makeArc14AuthHeader(signed);
 *   // send as: Authorization: <authorizationHeader>
 *   ```
 * - **.NET**: server-side verification here uses the
 *   [`AlgorandAuthentication`](https://www.nuget.org/packages/AlgorandAuthentication) NuGet package
 *   (see `AlgorandAuthenticationHandlerV2` in `Program.cs`); .NET clients can build the equivalent
 *   ARC-14 signed transaction directly with the [`Algorand4`](https://www.nuget.org/packages/Algorand4)
 *   SDK (construct a transaction with `Note` set to the realm, sign it with the account's private key,
 *   base64-encode it into the `Authorization` header) — there is no separate client-only package needed
 *   since the same SDK used to sign is already an `AVMTradeReporter` dependency.
 *
 * Short overview
 * - ASP.NET Core (.NET 10) Web API + SignalR service for streaming Algorand DEX activity (trades, liquidity, pools, blocks)
 * - Ingests data from Algod/Gossip, enriches via protocol-specific processors (Pact, Tiny, Biatec)
 * - Indexes documents in Elasticsearch and broadcasts live updates to clients via SignalR
 * - Optional Redis cache for assets and pools, plus background services for continuous operation
 *
 * Key capabilities
 * - Live SignalR hub at /biatecScanHub with recent updates and subscription-based filtering
 * - REST API for pool discovery and stats
 * - Background block processing and optional periodic pool refresh
 * - Swagger at /swagger using this document as the top-level description
 *
 * Architecture
 * - Web/API: Program.cs configures controllers, Swagger, CORS, authentication, SignalR
 * - Hubs: Hubs/BiatecScanHub.cs exposes methods, streams events, and manages client subscriptions
 * - Background services
 *   - TradeReporterBackgroundService: processes blocks, extracts trades and liquidity, updates Elasticsearch, publishes to hub
 *   - GossipBackgroundService: handles gossip websocket feed (see configuration)
 *   - PoolRefreshBackgroundService: optional periodic re-enrichment of pools
 * - Repositories
 *   - TradeRepository: Elasticsearch storage for trades, hub broadcast
 *   - LiquidityRepository: storage and hub broadcast for liquidity updates
 *   - PoolRepository and AggregatedPoolRepository: pool storage, enrichment, Redis integration, statistics
 *   - AssetRepository: asset metadata via Algod with optional Redis cache
 *   - BlockRepository: hub publishing for new blocks
 *   - IndexerRepository: progress tracking (round, genesis)
 *   - StatsRepository: read-only Elasticsearch sum aggregations for DefiLlama DEX stats export
 * - Processors (protocol-specific pool logic): PactPoolProcessor, TinyPoolProcessor, BiatecPoolProcessor
 * - Models: see AVMTradeReporter/Model/* (Trade, Liquidity, Pool, AggregatedPool, Block, configuration types)
 *
 * Data flow (high level)
 * 1) TradeReporterBackgroundService initializes pool cache, loads indexer progress
 * 2) Iterates blocks from Algod (with optional fallbacks), processes transactions
 * 3) Detects trades/liquidity/pool updates, enriches pools using protocol processors when needed
 * 4) Stores documents in Elasticsearch (data stream/index per type)
 * 5) Publishes recent updates to SignalR hub for clients
 *
 * Configuration
 * The app reads AppConfiguration and related sections from appsettings.json (or environment-specific variants).
 *
 * AppConfiguration
 * - IndexerId: string unique identifier for this indexer instance
 * - DelayMs: optional processing delay in milliseconds
 * - Direction: "+" or "-" to move forward or backward through rounds
 * - StartRound, MinRound, MaxRound: optional round bounds
 * - Algod, Algod2, Algod3: AlgodConfiguration endpoints (Host, ApiKey, Header)
 * - Elastic: ElasticConfiguration (Host, ApiKey)
 * - GossipWebsocketClientConfigurations: list of websocket peers (if used by gossip service). If the first entry's Host is empty (e.g. left unset via `AppConfiguration__GossipWebsocketClientConfigurations__0__Host`), the gossip service instead discovers all relays via DNS SRV, connects to all of them, and keeps only the fastest ones connected per GossipDiscovery.
 * - GossipDiscovery: dynamic relay discovery/ranking used when no gossip relay is statically configured
 *   - MaxActiveRelayConnections: how many relays to stay connected to once ranked (default 10)
 *   - WarmUpSeconds: how long to race all discovered relays before pruning down (default 120)
 *   - ReEvaluationIntervalSeconds: how often to check active relays' health once pruned (default 300)
 *   - StaleRelaySeconds: a connected relay silent for longer than this is replaced with a fresh candidate (default 600)
 * - Redis: RedisConfiguration
 *   - ConnectionString: e.g., localhost:6379
 *   - KeyPrefix: default avmtrade:pools:
 *   - Enabled: true/false
 *   - DatabaseId: integer DB id
 * - PoolRefresh: PoolRefreshConfiguration
 *   - Enabled: enable background refresh
 *   - IntervalHours: cadence of full refresh
 *   - DelayBetweenPoolsSeconds: throttle between pool refreshes
 *   - InitialDelayMinutes: startup delay before first cycle
 *
 * CORS
 * - Configure allowed origins under the Cors section; the app will fail startup if not provided
 *
 * Authentication
 * - Uses AlgorandAuthenticationV2 per Program.cs; see the "Authentication (ARC-0014)" section at the top of this document for how to generate a token as a client
 * - Swagger defines an API key scheme named arc14 (ARC-0014 Algorand authentication transaction transmitted in Authorization header)
 * - The SignalR pipeline moves access_token from query string to Authorization header for compatibility
 * - All REST endpoints require authentication ([Authorize]) except the following, which are intentionally public:
 *   - GET /api/asset/image/{assetId} (asset image, embedded directly as an <img> src)
 *   - GET /api/Gossip/status (relay connectivity health check)
 *   - GET /api/Stats/dex (DefiLlama DEX stats adapter integration)
 *   - GET /api/OHLC/* (TradingView UDF charting datafeed: config, time, symbols, symbol_info, search, marks, timescale_marks, quotes, history)
 *
 * Elasticsearch
 * - Client configured with ApiKey authentication and default mappings
 * - TradeRepository creates a template for trades-* as a data stream
 * - Mappings configured in Program.cs for:
 *   - Trade -> index "trades"
 *   - Liquidity -> index "liquidity"
 *   - AggregatedPool -> index "liquidity" (aggregates)
 *   - Pool -> index "pools"
 *   - Indexer -> index "indexers"
 *
 * SignalR hub (/biatecScanHub)
 * Client methods to call
 * - TestConnection(): returns connection/auth context
 * - Subscribe(filter): authorized; sets a user-specific filter string
 * - Unsubscribe(): authorized; clears subscription
 *
 * Server events you can receive
 * - Block: latest block metadata
 * - FilteredTradeUpdated: trade that passed your subscription filter
 * - FilteredLiquidityUpdated: liquidity event that passed your filter
 * - PoolUpdated: pool metadata update
 * - AggregatedPoolUpdated: aggregated pool update
 * - TestMessage: from test controller broadcast endpoint
 * - Subscribed / Unsubscribed: subscription acknowledgements
 *
 * Filter format examples
 * - protocol:Biatec
 * - asset:31566704
 * - trader:ALGORAND_ACCOUNT
 * - pool:123456
 * - pooladdress:ALGORAND_ADDRESS
 * - state:TxPool or Confirmed
 *
 * Typical JS client setup (pseudo)
 * - new signalR.HubConnectionBuilder().withUrl("/biatecScanHub?access_token=ALG_AUTH_TOKEN").build()
 * - await connection.start()
 * - await connection.invoke("Subscribe", "protocol:Biatec")
 * - connection.on("FilteredTradeUpdated", payload => { /* handle *\/ })
 *
 * REST API
 * - GET /api/pool
 *   - Query: assetIdA, assetIdB, protocol (Pact|Tiny|Biatec), size (default 100)
 *   - Returns list of pools (optionally filtered)
 * - GET /api/pool/{poolAddress}
 *   - Returns details for a specific pool address
 * - GET /api/pool/stats
 *   - Optional: assetIdA, assetIdB
 * - GET /api/stats/dex (no authentication required, designed for DefiLlama adapters)
 *   - Query: dex (Biatec|Pact|Tiny), timestamp (DateTimeOffset, inclusive window start)
 *   - Returns aggregated 24-hour statistics for the given DEX protocol over [timestamp, timestamp+1day)
 *   - Only confirmed trades are included in the aggregation
 *   - Response fields: protocol, from, to, volumeUSD, feesUSD, feesLPUSD, feesProtocolUSD
 *   - Powered by Elasticsearch sum aggregations on valueUSD, feesUSD, feesUSDProvider, feesUSDProtocol
 *   - Example: GET /api/stats/dex?dex=Biatec&timestamp=2024-01-15T00:00:00Z
 * - Test utilities (development)
 *   - GET /api/signalr/auth-test
 *   - GET /api/signalr/auth-test-authorized (requires auth)
 *   - POST /api/signalr/test-broadcast (requires auth)
 *   - POST /api/signalr/test-trade (requires auth)
 *
 * Pool enrichment and refresh
 * - Pools updated from trades or liquidity may miss metadata (e.g., approval program hash)
 * - PoolRepository can auto-enrich using protocol processors, with fallback between Tiny/Pact where appropriate
 * - Optional PoolRefreshBackgroundService periodically refreshes all pools
 * - See POOL_AUTO_ENRICHMENT.md and POOL_REFRESH_CONFIGURATION.md for deeper details
 *
 * Running locally
 * Prerequisites
 * - .NET 10 SDK
 * - Elasticsearch endpoint and API key
 * - Algod endpoint(s) and API key(s)
 * - Redis (optional but recommended)
 *
 * Steps
 * - Configure appsettings.Development.json with AppConfiguration, Cors, AlgorandAuthentication
 * - dotnet run in AVMTradeReporter
 * - Open /swagger to explore the API; this document appears as the description
 *
 * Notes
 * - GenerateDocumentationFile is enabled in AVMTradeReporter.csproj and Program.cs wires the generated
 *   AVMTradeReporter.xml into Swagger via IncludeXmlComments, so /// XML doc comments on controllers and
 *   actions are surfaced as operation summaries/descriptions in Swagger UI
 * - Swagger is served as OpenAPI 3.1 (app.UseSwagger sets OpenApiVersion = OpenApi3_1 in Program.cs)
 * - DockerDefaultTargetOS is Linux; containerization supported via standard ASP.NET Core tooling
 * - Tests live in AVMTradeReporterTests (NUnit)
 *
 * Troubleshooting
 * - If SignalR auth fails, ensure access_token query string contains the Algorand auth value and that CORS allows your origin
 * - If startup fails due to CORS, add origins under Cors in configuration
 * - If Elasticsearch calls fail, verify Host/ApiKey and network access
 * - If Algod calls fail, verify Algod Host/ApiKey/Header and optional fallbacks Algod2/Algod3
 * - Logs include detailed diagnostics for SignalR, authentication, and background processing
 *
 * OpenAPI spec version: v1
 */
import type {
  AggregatedPool,
  AssetStat,
  AssetTimeseries7D,
  BiatecAsset,
  DexStatsResponse,
  GetApiAggregatedPoolParams,
  GetApiAggregatedPoolReloadParams,
  GetApiAssetParams,
  GetApiAssetStatAssetIdParams,
  GetApiAssetStatParams,
  GetApiAssetTimeseries7dParams,
  GetApiLiquidityParams,
  GetApiOHLCHistoryParams,
  GetApiOHLCQuotesParams,
  GetApiOHLCSearchParams,
  GetApiOHLCSymbolInfoParams,
  GetApiOHLCSymbolsParams,
  GetApiPoolParams,
  GetApiPoolReloadParams,
  GetApiPoolStatsParams,
  GetApiSearchParams,
  GetApiStatsDexParams,
  GetApiTradeParams,
  GossipRelayStatus,
  Indexer,
  Liquidity,
  Pool,
  SearchResponse,
  TopAssetsResponse,
  TradePagedResult
} from './models';

import { axiosInstance } from './axios-instance';
export const getAVMTradeReporterAPI = () => {
/**
 * @summary Get all aggregated pools or filter by asset ids. An asset id filter matches the asset on either side of the pair.
 */
const getApiAggregatedPool = (
    params?: GetApiAggregatedPoolParams,
 ) => {
      return axiosInstance<AggregatedPool[]>(
      {url: `/api/aggregated-pool`, method: 'GET',
        params
    },
      );
    }

/**
 * @summary Update and retrieve aggregated pool
 */
const getApiAggregatedPoolReload = (
    params?: GetApiAggregatedPoolReloadParams,
 ) => {
      return axiosInstance<AggregatedPool>(
      {url: `/api/aggregated-pool/reload`, method: 'GET',
        params
    },
      );
    }

/**
 * @summary List assets from the in-memory cache (prefilled from Redis) or filter by IDs / search term.
 */
const getApiAsset = (
    params?: GetApiAssetParams,
 ) => {
      return axiosInstance<BiatecAsset[]>(
      {url: `/api/asset`, method: 'GET',
        params
    },
      );
    }

/**
 * @summary Returns the cached PNG image for the given asset id. Intentionally public (no authentication
required) so it can be embedded directly as an <img> src in browsers/clients without an
ARC-14 signed transaction.
 */
const getApiAssetImageAssetId = (
    assetId: number,
 ) => {
      return axiosInstance<Blob>(
      {url: `/api/asset/image/${assetId}`, method: 'GET',
        responseType: 'blob'
    },
      );
    }

/**
 * @summary Get backend-computed per-asset TVL/volume/fees/APR stats, optionally filtered by protocol.
 */
const getApiAssetStat = (
    params?: GetApiAssetStatParams,
 ) => {
      return axiosInstance<AssetStat[]>(
      {url: `/api/asset-stat`, method: 'GET',
        params
    },
      );
    }

/**
 * @summary Get the stat row for a single asset, optionally scoped to a protocol.
 */
const getApiAssetStatAssetId = (
    assetId: number,
    params?: GetApiAssetStatAssetIdParams,
 ) => {
      return axiosInstance<AssetStat>(
      {url: `/api/asset-stat/${assetId}`, method: 'GET',
        params
    },
      );
    }

/**
 * @summary Get the 7 day hourly timeseries (USD price OHLC and real TVL OHLC candles) for up to 100
assets at once, for the sparkline/candle columns on the asset and pool list pages. Series
are recomputed on a 1 hour cadence and served from the Redis cache in between, so this
endpoint is cheap to call for a whole page of assets.
 */
const getApiAssetTimeseries7d = (
    params?: GetApiAssetTimeseries7dParams,
 ) => {
      return axiosInstance<AssetTimeseries7D[]>(
      {url: `/api/asset/timeseries/7d`, method: 'GET',
        params
    },
      );
    }

/**
 * @summary Returns the set of gossip relays currently connected (or being connected to), along with how many
mempool messages each has delivered and when it last delivered one.
 */
const getApiGossipStatus = (

 ) => {
      return axiosInstance<GossipRelayStatus[]>(
      {url: `/api/Gossip/status`, method: 'GET'
    },
      );
    }

/**
 * @summary Gets the current indexer status
 */
const getApiIndexerStatus = (

 ) => {
      return axiosInstance<Indexer>(
      {url: `/api/indexer/status`, method: 'GET'
    },
      );
    }

/**
 * @summary Get liquidity updates with optional filtering and pagination.
 */
const getApiLiquidity = (
    params?: GetApiLiquidityParams,
 ) => {
      return axiosInstance<Liquidity[]>(
      {url: `/api/liquidity`, method: 'GET',
        params
    },
      );
    }

/**
 * @summary Returns the TradingView UDF datafeed configuration (supported resolutions, exchanges, symbol types).
 */
const getApiOHLCConfig = (

 ) => {
      return axiosInstance<void>(
      {url: `/api/OHLC/config`, method: 'GET'
    },
      );
    }

/**
 * @summary Returns the current server time as a Unix timestamp, used by TradingView for datafeed sync.
 */
const getApiOHLCTime = (

 ) => {
      return axiosInstance<void>(
      {url: `/api/OHLC/time`, method: 'GET'
    },
      );
    }

/**
 * @summary Resolves a single symbol (e.g. "31566704_0") to its TradingView symbol info.
 */
const getApiOHLCSymbols = (
    params?: GetApiOHLCSymbolsParams,
 ) => {
      return axiosInstance<void>(
      {url: `/api/OHLC/symbols`, method: 'GET',
        params
    },
      );
    }

/**
 * @summary Resolves a comma separated group of symbols to their TradingView symbol info in bulk.
 */
const getApiOHLCSymbolInfo = (
    params?: GetApiOHLCSymbolInfoParams,
 ) => {
      return axiosInstance<void>(
      {url: `/api/OHLC/symbol_info`, method: 'GET',
        params
    },
      );
    }

/**
 * @summary Searches for tradable symbols (asset pairs) matching a free-text query, for the TradingView symbol search box.
 */
const getApiOHLCSearch = (
    params?: GetApiOHLCSearchParams,
 ) => {
      return axiosInstance<void>(
      {url: `/api/OHLC/search`, method: 'GET',
        params
    },
      );
    }

/**
 * @summary Returns chart marks (annotations) for the TradingView datafeed. Currently always empty.
 */
const getApiOHLCMarks = (

 ) => {
      return axiosInstance<void>(
      {url: `/api/OHLC/marks`, method: 'GET'
    },
      );
    }

/**
 * @summary Returns timescale marks for the TradingView datafeed. Currently always empty.
 */
const getApiOHLCTimescaleMarks = (

 ) => {
      return axiosInstance<void>(
      {url: `/api/OHLC/timescale_marks`, method: 'GET'
    },
      );
    }

/**
 * @summary Returns last-quote snapshots for the given symbols, for the TradingView quotes API.
 */
const getApiOHLCQuotes = (
    params?: GetApiOHLCQuotesParams,
 ) => {
      return axiosInstance<void>(
      {url: `/api/OHLC/quotes`, method: 'GET',
        params
    },
      );
    }

/**
 * @summary Returns OHLCV bars for an asset pair over a time range, for the TradingView history API.
 */
const getApiOHLCHistory = (
    params?: GetApiOHLCHistoryParams,
 ) => {
      return axiosInstance<void>(
      {url: `/api/OHLC/history`, method: 'GET',
        params
    },
      );
    }

/**
 * @summary Get all pools or filter by protocol
 */
const getApiPool = (
    params?: GetApiPoolParams,
 ) => {
      return axiosInstance<Pool[]>(
      {url: `/api/pool`, method: 'GET',
        params
    },
      );
    }

/**
 * @summary Get pool statistics
 */
const getApiPoolStats = (
    params?: GetApiPoolStatsParams,
 ) => {
      return axiosInstance<void>(
      {url: `/api/pool/stats`, method: 'GET',
        params
    },
      );
    }

/**
 * @summary Get pool statistics
 */
const getApiPoolReload = (
    params?: GetApiPoolReloadParams,
 ) => {
      return axiosInstance<void>(
      {url: `/api/pool/reload`, method: 'GET',
        params
    },
      );
    }

/**
 * @summary Searches assets and pools matching the given query term.
 */
const getApiSearch = (
    params?: GetApiSearchParams,
 ) => {
      return axiosInstance<SearchResponse>(
      {url: `/api/search`, method: 'GET',
        params
    },
      );
    }

/**
 * @summary Returns the caller's current authentication state and claims, for debugging ARC-14 auth.
 */
const getApiSignalrAuthTest = (

 ) => {
      return axiosInstance<void>(
      {url: `/api/signalr/auth-test`, method: 'GET'
    },
      );
    }

/**
 * @summary Same as M:AVMTradeReporter.Controllers.SignalRTestController.AuthTest but forces authorization at the action level (redundant given the class-level [Authorize], kept explicit for clarity/testing).
 */
const getApiSignalrAuthTestAuthorized = (

 ) => {
      return axiosInstance<void>(
      {url: `/api/signalr/auth-test-authorized`, method: 'GET'
    },
      );
    }

/**
 * @summary Broadcasts a test info message to all connected SignalR clients.
 */
const postApiSignalrTestBroadcast = (
    postApiSignalrTestBroadcastBody?: string,
 ) => {
      return axiosInstance<void>(
      {url: `/api/signalr/test-broadcast`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiSignalrTestBroadcastBody
    },
      );
    }

/**
 * @summary Broadcasts a synthetic test trade to all connected SignalR clients, for verifying the trade event pipeline end to end.
 */
const postApiSignalrTestTrade = (

 ) => {
      return axiosInstance<void>(
      {url: `/api/signalr/test-trade`, method: 'POST'
    },
      );
    }

/**
 * @summary Returns the current count and list of active SignalR hub subscriptions.
 */
const getApiSignalrConnections = (

 ) => {
      return axiosInstance<void>(
      {url: `/api/signalr/connections`, method: 'GET'
    },
      );
    }

/**
 * @summary Returns aggregated 24-hour DEX statistics (volume, fees) for the given protocol starting at
timestamp. The query window is [timestamp, timestamp + 1 day).
Only confirmed trades are included. Suitable for DefiLlama adapter consumption.
 */
const getApiStatsDex = (
    params?: GetApiStatsDexParams,
 ) => {
      return axiosInstance<DexStatsResponse>(
      {url: `/api/Stats/dex`, method: 'GET',
        params
    },
      );
    }

/**
 * @summary Get the "top assets" highlight lists for the scan homepage header: Popular (24h volume),
Trending (1h volume), Top gainers/losers (24h price change in percent) and Top liquidity
gainers/losers (24h real TVL change in percent). Candidates are the top 150 assets by real TVL excluding stable assets;
each list holds up to 3 entries. The response is recomputed every 5 minutes and served from
the Redis cache in between.
 */
const getApiAssetTop = (

 ) => {
      return axiosInstance<TopAssetsResponse>(
      {url: `/api/asset/top`, method: 'GET'
    },
      );
    }

/**
 * @summary Get trades with optional filtering and pagination.
 */
const getApiTrade = (
    params?: GetApiTradeParams,
 ) => {
      return axiosInstance<TradePagedResult>(
      {url: `/api/trade`, method: 'GET',
        params
    },
      );
    }

return {getApiAggregatedPool,getApiAggregatedPoolReload,getApiAsset,getApiAssetImageAssetId,getApiAssetStat,getApiAssetStatAssetId,getApiAssetTimeseries7d,getApiGossipStatus,getApiIndexerStatus,getApiLiquidity,getApiOHLCConfig,getApiOHLCTime,getApiOHLCSymbols,getApiOHLCSymbolInfo,getApiOHLCSearch,getApiOHLCMarks,getApiOHLCTimescaleMarks,getApiOHLCQuotes,getApiOHLCHistory,getApiPool,getApiPoolStats,getApiPoolReload,getApiSearch,getApiSignalrAuthTest,getApiSignalrAuthTestAuthorized,postApiSignalrTestBroadcast,postApiSignalrTestTrade,getApiSignalrConnections,getApiStatsDex,getApiAssetTop,getApiTrade}};
export type GetApiAggregatedPoolResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiAggregatedPool']>>>
export type GetApiAggregatedPoolReloadResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiAggregatedPoolReload']>>>
export type GetApiAssetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiAsset']>>>
export type GetApiAssetImageAssetIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiAssetImageAssetId']>>>
export type GetApiAssetStatResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiAssetStat']>>>
export type GetApiAssetStatAssetIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiAssetStatAssetId']>>>
export type GetApiAssetTimeseries7dResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiAssetTimeseries7d']>>>
export type GetApiGossipStatusResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiGossipStatus']>>>
export type GetApiIndexerStatusResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiIndexerStatus']>>>
export type GetApiLiquidityResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiLiquidity']>>>
export type GetApiOHLCConfigResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiOHLCConfig']>>>
export type GetApiOHLCTimeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiOHLCTime']>>>
export type GetApiOHLCSymbolsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiOHLCSymbols']>>>
export type GetApiOHLCSymbolInfoResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiOHLCSymbolInfo']>>>
export type GetApiOHLCSearchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiOHLCSearch']>>>
export type GetApiOHLCMarksResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiOHLCMarks']>>>
export type GetApiOHLCTimescaleMarksResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiOHLCTimescaleMarks']>>>
export type GetApiOHLCQuotesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiOHLCQuotes']>>>
export type GetApiOHLCHistoryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiOHLCHistory']>>>
export type GetApiPoolResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiPool']>>>
export type GetApiPoolStatsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiPoolStats']>>>
export type GetApiPoolReloadResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiPoolReload']>>>
export type GetApiSearchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiSearch']>>>
export type GetApiSignalrAuthTestResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiSignalrAuthTest']>>>
export type GetApiSignalrAuthTestAuthorizedResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiSignalrAuthTestAuthorized']>>>
export type PostApiSignalrTestBroadcastResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['postApiSignalrTestBroadcast']>>>
export type PostApiSignalrTestTradeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['postApiSignalrTestTrade']>>>
export type GetApiSignalrConnectionsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiSignalrConnections']>>>
export type GetApiStatsDexResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiStatsDex']>>>
export type GetApiAssetTopResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiAssetTop']>>>
export type GetApiTradeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAVMTradeReporterAPI>['getApiTrade']>>>
