apiVersion: apps/v1
kind: Deployment
metadata:
  name: biatec-scan-fe-app-deployment
  namespace: biatec-scan
spec:
  selector:
    matchLabels:
      app: biatec-scan-fe-app
  replicas: 1
  template:
    metadata:
      labels:
        app: biatec-scan-fe-app
    spec:
      containers:
        - name: biatec-scan-fe-app
          image: scholtz2/biatec-scan-fe:1.2025.08.12-main
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: "200Mi"
            limits:
              cpu: 2000m
              memory: "1000Mi"
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 5
            failureThreshold: 2
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 5
            failureThreshold: 2
            terminationGracePeriodSeconds: 1
          volumeMounts:
            - name: biatec-scan-fe-main-conf
              mountPath: /app/appsettings.json
              subPath: appsettings.json
      volumes:
        - name: biatec-scan-fe-main-conf
          configMap:
            name: biatec-scan-fe-main-conf
---
apiVersion: v1
kind: Service
metadata:
  name: biatec-scan-fe-service
  namespace: biatec-scan
spec:
  type: ClusterIP
  selector:
    app: biatec-scan-fe-app
  ports:
    - name: http
      protocol: TCP
      appProtocol: http
      port: 8080
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: biatec-scan-algorand-ingress-main
  namespace: biatec-scan
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - algorand.scan.biatec.io
      secretName: tls-algorand.scan.biatec.io
  rules:
    - host: algorand.scan.biatec.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: biatec-scan-fe-service
                port:
                  number: 8080
