/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * AVM Trade Reporter API
 * OpenAPI spec version: v1
 */
import type { DEXProtocol } from './dEXProtocol';
import type { TxState } from './txState';

export interface Liquidity {
  assetIdA?: number;
  assetIdB?: number;
  assetIdLP?: number;
  assetAmountA?: number;
  assetAmountB?: number;
  assetAmountLP?: number;
  /** @nullable */
  txId?: string | null;
  blockId?: number;
  /** @nullable */
  txGroup?: string | null;
  /** @nullable */
  timestamp?: string | null;
  protocol?: DEXProtocol;
  /** @nullable */
  liquidityProvider?: string | null;
  /** @nullable */
  poolAddress?: string | null;
  poolAppId?: number;
  /** @nullable */
  topTxId?: string | null;
  txState?: TxState;
  /** @nullable */
  direction?: string | null;
  a?: number;
  b?: number;
  l?: number;
}